use crate::mus::{
    Accion, Baraja, CuatroJugadores, DosJugadores, Lance, Mano, ModalidadMus, PartidaMus, Turno,
};

use super::{Agent, Kibitzer};

/// Events generated by MusArena during a game.
#[derive(Clone, Debug)]
pub enum MusAction {
    /// Game starts. It contains the index of the dealer and the scoreboard at the start of the
    /// game.
    GameStart { hand: usize, scoreboard: [u8; 2] },
    /// Cards are dealed to players. It contains the index of the player receiving its cards and
    /// the hand itself.
    DealHand(usize, Mano),
    /// A new lance starts.
    LanceStart(Lance),
    /// A player acts. It contains the index of the player acting and the corresponding action.
    PlayerAction(usize, Accion),
    /// The payoff received by each player at the end of the game. It contains the index of the
    /// player receiving the payoff and the payoff itself.
    Payoff(usize, u8),
}

/// Simulates a mus game or a particular lance.
pub struct MusArena<T: ModalidadMus> {
    pub agents: Vec<Box<dyn Agent<T> + Send>>,
    pub kibitzers: Vec<Box<dyn Kibitzer<T> + Send>>,
    partida_mus: PartidaMus<T>,
    lance: Option<Lance>,
    order: Vec<usize>,
    scoreboard: [u8; 2],
    init_scoreboard: [u8; 2],
}

impl<T: ModalidadMus> MusArena<T> {
    fn record_action(&mut self, a: MusAction) {
        self.kibitzers
            .iter_mut()
            .for_each(|k| k.record(&self.partida_mus, a.clone()));
    }

    fn report_payoff(&mut self, scoreboard: &[u8; 2]) -> [u8; 2] {
        let new_scoreboard = self.partida_mus.tantos().clone();
        for i in 0..self.order.len() {
            if new_scoreboard[i] != scoreboard[i] {
                self.record_action(MusAction::Payoff(
                    self.order[i],
                    new_scoreboard[i] - scoreboard[i],
                ));
            }
        }
        new_scoreboard
    }
}

impl MusArena<DosJugadores> {
    pub fn new(init_scoreboard: [u8; 2], lance: Option<Lance>) -> Self {
        MusArena {
            agents: vec![],
            kibitzers: vec![],
            partida_mus: Self::new_partida(lance, init_scoreboard),
            order: vec![0, 1],
            lance,
            scoreboard: init_scoreboard,
            init_scoreboard,
        }
    }

    fn new_partida(lance: Option<Lance>, scoreboard: [u8; 2]) -> PartidaMus<DosJugadores> {
        let baraja = Baraja::baraja_mus();
        match lance {
            None => {
                let manos = baraja.repartir_manos();
                PartidaMus::<DosJugadores>::new([manos[0].clone(), manos[1].clone()], scoreboard)
            }
            Some(_) => loop {
                todo!()
            },
        }
    }

    pub async fn start(&mut self) {
        self.order.rotate_left(1);
        if self.scoreboard[0] == 40 || self.scoreboard[1] == 40 {
            self.scoreboard = self.init_scoreboard;
        }
        let mut scoreboard = [
            self.scoreboard[self.order[0]],
            self.scoreboard[self.order[1]],
        ];
        self.partida_mus = MusArena::<DosJugadores>::new_partida(self.lance, scoreboard);
        self.record_action(MusAction::GameStart {
            hand: self.order[0],
            scoreboard: self.scoreboard,
        });
        let manos = self.partida_mus.manos().clone();
        for i in 0..manos.len() {
            self.record_action(MusAction::DealHand(self.order[i], manos[i].clone()));
        }
        let mut lance = self.partida_mus.lance_actual();
        self.record_action(MusAction::LanceStart(lance.unwrap()));
        while let Some(turno) = self.partida_mus.turno() {
            let player_id = match turno {
                Turno::Jugador(id) | Turno::Pareja(id) => id,
            } as usize;
            let accion = self.agents[self.order[player_id]]
                .actuar(&self.partida_mus)
                .await;
            if self.partida_mus.actuar(accion).is_ok() {
                self.record_action(MusAction::PlayerAction(self.order[player_id], accion));
                scoreboard = self.report_payoff(&scoreboard);
                let nuevo_lance = self.partida_mus.lance_actual();
                if nuevo_lance != lance {
                    lance = nuevo_lance;
                    if let Some(l) = lance {
                        self.record_action(MusAction::LanceStart(l));
                    }
                }
            }
        }
        self.scoreboard = self.report_payoff(&scoreboard);
    }
}

impl MusArena<CuatroJugadores> {
    pub fn new(init_scoreboard: [u8; 2], lance: Option<Lance>) -> Self {
        MusArena {
            agents: vec![],
            kibitzers: vec![],
            partida_mus: Self::new_partida(lance),
            order: vec![0, 1, 2, 3],
            lance,
            scoreboard: init_scoreboard,
            init_scoreboard,
        }
    }

    fn new_partida(lance: Option<Lance>) -> PartidaMus<CuatroJugadores> {
        let mut baraja = Baraja::baraja_mus();
        match lance {
            None => {
                let manos = baraja.repartir_manos();
                PartidaMus::<CuatroJugadores>::new(manos, [0, 0])
            }
            Some(lance) => loop {
                baraja.barajar();
                let manos = baraja.repartir_manos();
                let posible_partida_mus =
                    PartidaMus::<CuatroJugadores>::new_partida_lance(lance, manos, [0, 0]);
                if let Some(partida_mus) = posible_partida_mus {
                    return partida_mus;
                }
            },
        }
    }

    pub async fn start(&mut self) {
        self.partida_mus = MusArena::<CuatroJugadores>::new_partida(self.lance);
        self.order.rotate_left(1);
        self.record_action(MusAction::GameStart {
            hand: self.order[0],
            scoreboard: *self.partida_mus.tantos(),
        });
        let manos = self.partida_mus.manos().clone();
        for (i, m) in manos.iter().enumerate() {
            self.record_action(MusAction::DealHand(self.order[i], m.clone()));
        }
        let mut lance = self.partida_mus.lance_actual();
        self.record_action(MusAction::LanceStart(lance.unwrap()));
        while let Some(turno) = self.partida_mus.turno() {
            let player_id = match turno {
                Turno::Jugador(id) | Turno::Pareja(id) => id,
            } as usize;
            let accion = self.agents[self.order[player_id]]
                .actuar(&self.partida_mus)
                .await;
            if self.partida_mus.actuar(accion).is_ok() {
                self.record_action(MusAction::PlayerAction(self.order[player_id], accion));
                let nuevo_lance = self.partida_mus.lance_actual();
                if nuevo_lance != lance {
                    lance = nuevo_lance;
                    if let Some(l) = lance {
                        self.record_action(MusAction::LanceStart(l));
                    }
                }
            }
        }
        let tantos = *self.partida_mus.tantos();
        self.record_action(MusAction::Payoff(self.order[0] % 2, tantos[0]));
        self.record_action(MusAction::Payoff(self.order[1] % 2, tantos[1]));
    }
}
