[package]
name = "inspector"
version = "0.1.0"
edition = "2021"

[dependencies]
musolver = { path = ".." }
iced = { version = "0.13.1", features = ["canvas"] }
itertools.workspace = true
async-trait.workspace = true
image = "0.25.5"
